id: DBF36F08B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:30:50+00:00'
last_modified: '2022-05-27T09:39:23.771613+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a864:
      image_group_id: I1PD95903
      title: དབུ་མའི་སྙིང་པོའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1649
      order: 58
      base_file: a864.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
