id: 3a4e94d524ae402fa1e671aed5597e30
initial_creation_type: ocr
source_metadata:
  volumes:
    b5fad783ba0e43ab9f311ec486d91b9d:
      base_file: v057.txt
      image_group_id: I1PD95903
      title: དབུ་མའི་སྙིང་པོའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1649
      volume_number: 58
